# -*- coding: utf-8 -*-
"""Vale3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYzwYxbAfNkIRP59RzGPdSGSrQvZcT35
"""

!pip install yfinance pandas openpyxl

# Exemplo: vale
periodo = "5y"      # Último 5 ano de dados

# 2. Baixar os dados do Yahoo Finance
dados = yf.download(ticker, period=periodo)

# Tratamento para versões recentes do yfinance (ajusta o cabeçalho se necessário)
if isinstance(dados.columns, pd.MultiIndex):
    dados.columns = dados.columns.get_level_values(0)

# 3. Salvar DIRETAMENTE como arquivo Excel (.xlsx)
vale3_arquivo = f"{ticker}_historico.xlsx"
dados.to_excel(vale3_arquivo)

print(f"Planilha Excel baixada e salva com sucesso como: {vale3_arquivo}!")
print(dados.head())

# A planilha acima veio organizada e no formato ideal para utilizar no Power BI.